/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChangeSize: typeof import('./src/components/contents/config-theme/components/change-size.vue')['default']
    ChangeTheme: typeof import('./src/components/contents/config-theme/components/change-theme.vue')['default']
    ConfigTheme: typeof import('./src/components/contents/config-theme/index.vue')['default']
    IconButton: typeof import('./src/components/components/icon-button/index.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NFlex: typeof import('naive-ui')['NFlex']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvid: typeof import('naive-ui')['NLoadingBarProvid']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NTab: typeof import('naive-ui')['NTab']
    NTabs: typeof import('naive-ui')['NTabs']
    NTooltip: typeof import('naive-ui')['NTooltip']
    ResetTheme: typeof import('./src/components/contents/config-theme/components/reset-theme.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwitchLang: typeof import('./src/components/contents/config-theme/components/switch-lang.vue')['default']
    SwitchLayout: typeof import('./src/components/contents/config-theme/components/switch-layout.vue')['default']
    ToggleDark: typeof import('./src/components/contents/config-theme/components/toggle-dark.vue')['default']
    ToggleTransition: typeof import('./src/components/contents/config-theme/components/toggle-transition.vue')['default']
  }
}
